### ISSUE TITLE
Time intervals

### ISSUE THREAD

**Issue by arnau** [arnau/ISO8601#15]
Add support for time intervals:
```
<start>/<end>
<start>/<duration>
<duration>/<end>
```

Examples:

Start and end, such as "2007-03-01T13:00:00Z/2008-05-11T15:30:00Z"
Start and duration, such as "2007-03-01T13:00:00Z/P1Y2M10DT2H30M"
Duration and end, such as "P1Y2M10DT2H30M/2008-05-11T15:30:00Z"

**Comment by Angelmmiguel** [comment]
Hello,

I'm using your gem and I need to work with Time intervals. I will clone your gem and start with this feature. Did you advance with it?

Thanks!

**Comment by arnau** [comment]
Hi, glad to hear that :)  I didn't start with it yet

**Comment by Angelmmiguel** [comment]
Ok, I will try to implement this feature :)

**Comment by Angelmmiguel** [comment]
I have started this feature in my branch [feature/time_intervals](https://github.com/redBorder/ISO8601/tree/feature/time_intervals).

**Comment by Angelmmiguel** [comment]
I think I finished the first version of this class :). I'll make a pull request to discuss TimeInterval class.

**Comment by arnau** [comment]
Nice, I'm not going to be able to dedicate much time this week but as soon as I can I'll jump in.

**Comment by Angelmmiguel** [comment]
ok!

**Comment by arnau** [comment]
Released with 0.9.0
