### ISSUE TITLE
DateTime.new fails to parse YYYY-MM-DDThh:mmZ format 

### ISSUE THREAD

**Issue by runwaldarshu** [arnau/ISO8601#20]
Following test case failed 
``` expect { ISO8601::DateTime.new('2015-01-17T10:30Z') }.to_not raise_error```
 error
``` expected no Exception, got #<NoMethodError: undefined method `div' for "Z":String> with backtrace: ```
YYYY-MM-DDThh:mmZ seems to be the valid ISO8601 format

**Comment by arnau** [comment]
@runwaldarshu what ruby implementation did you use for getting this error?

**Comment by arnau** [comment]
I found the case of error, it's fixed in master and in 0.8.3

**Comment by runwaldarshu** [comment]
There is one out left in the commit https://github.com/arnau/ISO8601/commit/039c7c85a0691f5201f9c5ffe268d836d408b6eb
