### ISSUE TITLE
Hash function has to be improved.

### ISSUE THREAD

**Issue by runwaldarshu** [arnau/ISO8601#21]
Current hash function of ISO8601::DateTime has some issues due to only looking at seconds and fraction seconds part and that causes following
```
2.1.5 :004 > ISO8601::DateTime.new('2014') == ISO8601::DateTime.new('2015')
 => true
```
There are many other cases which fall through this.

A possible fix I could see is 
[self.to_time.to_f, self.class].hash
or even add little more variables to it.

**Comment by arnau** [comment]
@runwaldarshu I won't be able to look into it today, but your proposal seems good to me.

**Comment by runwaldarshu** [comment]
No problem @arnau Thanks for the quick reply.

**Comment by arnau** [comment]
@runwaldarshu seemed a quick fix so I fix it in `bugs/dateTime-identity` branch.  Could you double check it works for you?  I added a couple more tests to cover all loose dateTimes so it should be fine.

I'll take a second look tomorrow and merge to master if everything looks fine.

**Comment by arnau** [comment]
I'm thinking after releasing this as a fix, a good enhancement would be making sure different representations for the same time respond to true (say, differences because timezone, etc.)

**Comment by arnau** [comment]
Fixed with your proposal.  Will be on the next release, for now in `master`
