### ISSUE TITLE
DateTime doen't support timezone offset format ±[hh][mm]

### ISSUE THREAD

**Issue by sambao21** [arnau/ISO8601#24]
Currently, DateTime has an issue parsing timezone offset format ±[hh][mm].

```ruby
irb(main):036:0> ISO8601::DateTime.new("2015-03-19T20:35:58Z")
=> #<ISO8601::DateTime:0x007fa75bb4f820 @original="2015-03-19T20:35:58Z", @date_time=#<DateTime: 2015-03-19T20:35:58+00:00 ((2457101j,74158s,0n),+0s,2299161j)>, @second=58.0>
irb(main):037:0> ISO8601::DateTime.new("2015-03-19T20:35:58+00")
=> #<ISO8601::DateTime:0x007fa75bb3eed0 @original="2015-03-19T20:35:58+00", @date_time=#<DateTime: 2015-03-19T20:35:58+00:00 ((2457101j,74158s,0n),+0s,2299161j)>, @second=58.0>
irb(main):038:0> ISO8601::DateTime.new("2015-03-19T20:35:58+00:00")
=> #<ISO8601::DateTime:0x007fa75bb2e030 @original="2015-03-19T20:35:58+00:00", @date_time=#<DateTime: 2015-03-19T20:35:58+00:00 ((2457101j,74158s,0n),+0s,2299161j)>, @second=58.0>
irb(main):039:0> ISO8601::DateTime.new("2015-03-19T20:35:58+0000")
ISO8601::Errors::UnknownPattern: Unknown pattern 20:35:58+0000
	from /Users/sb012532/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/iso8601-0.8.5/lib/iso8601/time.rb:123:in `atomize'
	from /Users/sb012532/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/iso8601-0.8.5/lib/iso8601/time.rb:36:in `initialize'
	from /Users/sb012532/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/iso8601-0.8.5/lib/iso8601/date_time.rb:128:in `new'
	from /Users/sb012532/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/iso8601-0.8.5/lib/iso8601/date_time.rb:128:in `parse_time'
	from /Users/sb012532/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/iso8601-0.8.5/lib/iso8601/date_time.rb:99:in `parse'
	from /Users/sb012532/.rbenv/versions/2.2.1/lib/ruby/gems/2.2.0/gems/iso8601-0.8.5/lib/iso8601/date_time.rb:25:in `initialize'
	from (irb):39:in `new'
	from (irb):39
	from /Users/sb012532/.rbenv/versions/2.2.1/bin/irb:11:in `<main>'
```

I would be willing to submit a solution once I have time.

**Comment by arnau** [comment]
Hi, this behaviour is intended to be that way. Either you use a compact representation (no separators, i.e. `YYYYMMDDThhmmss±hhmm`) or you use the full representation (`YYYY-MM-DDThh:mm:ss±hh:mm`.)

In the same way, you cannot do mixed representations between the date part and the time part (`YYYY-MM-DDThhmmssZ`.)

**Comment by sambao21** [comment]
Thanks for the response. Could you perhaps help me understand why you went with this behavior? Searching around, it certainly looks like nothing ever does mixes, but is it invalid iso8601 format to mix and match between basic format (no separators) and the full representation or just bad, or awkward, practice?

**Comment by arnau** [comment]
I reviewed the wikipedia entry as is the reference I'm using to implement the spec.  There is an explicit statement of not using a mixed formats:

> Either basic or extended formats may be used, but both date and time must use the same format — https://en.wikipedia.org/wiki/ISO_8601#Combined_date_and_time_representations

Then, I tend to agree with http://www.w3.org/TR/NOTE-datetime where they restrict the allowed format to extended only (they do more restrictions but this one is the one that matters in this case.)

> On the Internet, the World Wide Web Consortium (W3C) uses ISO 8601 in defining a profile of the standard that restricts the supported date and time formats to reduce the chance of error and the complexity of software — https://en.wikipedia.org/wiki/ISO_8601#Usage

Did you face any real use case where you had to manage datetimes with mixed formats?

**Comment by sambao21** [comment]
Thank you for the references. We have not, but we are currently using iso8601 in our own library that adds on some of our own functional requirements for comparison operations, and wanted it to the be robust enough to handle the ±[hh][mm] offset format. We'll have to handle it appropriately, but you're probably right though in that we don't ever get it mixed.
