### ISSUE TITLE
Problem with minute offsets when the time is only specified to the hour

### ISSUE THREAD

**Issue by gravesb** [arnau/ISO8601#25]
Currently, DateTime raises an UnknownPattern error when parsing timezone offsets with the format YYYY-MM-DDThh+[hh]:[mm] or YYYY-MM-DDThh+[hh][mm].  I couldn't find anything on the ISO8601 wiki page that indicates those formats would be disallowed or invalid.  Is this intentional or is it a bug?

````
2.1.5 :001 > ISO8601::DateTime.new("2015-04-13T20+00")
 => #<ISO8601::DateTime:0x007ffdfeab06e0 @original="2015-04-13T20+00", @date_time=#<DateTime: 2015-04-13T20:00:00+00:00 ((2457126j,72000s,0n),+0s,2299161j)>, @second=0.0>
2.1.5 :003 >   ISO8601::DateTime.new("2015-04-13T20+00:00")
ISO8601::Errors::UnknownPattern: Unknown pattern 20+00:00
````

**Comment by arnau** [comment]
As far as I understand it is a bug as the timezone attach to a time component `<time>±hh:mm`.

Thanks for reporting!

**Comment by arnau** [comment]
@gravesb release planned: 0.8.6

**Comment by gravesb** [comment]
Awesome, thanks for the quick turnaround on this.
