### ISSUE TITLE
-00 and -00:00 are accepted as timezone

### ISSUE THREAD

**Issue by runwaldarshu** [arnau/ISO8601#27]
Based on iso8601 standard for UTC\[1] "−00:00" or "−00" are not valid formats but currently when we pass it to ISO8601::DateTime class these values are accepted and then get converted into +00:00.
Is this an issue or intended behaviour? 

\[1]: http://en.wikipedia.org/wiki/ISO_8601#UTC

**Comment by arnau** [comment]
It is intended that way for simplicity sake.  Do you think it is a problem besides not being strict with the spec restrictions?

**Comment by runwaldarshu** [comment]
No I do not think there is any problem just wanted to know.
Thanks.
