### ISSUE TITLE
Incorrect start date on TimeIntervals anchored in the month of December

### ISSUE THREAD

**Issue by komputerwiz** [arnau/ISO8601#40]
Some cases:

```ruby
ISO8601::TimeInterval.new("P1Y/2017-12-06T18:30:00Z").first.to_s
# => "2015-12-07T18:30:00+00:00" expected: "2017-12-06T18:30:00+00:00"
ISO8601::TimeInterval.new("P2M/2017-12-06T18:30:00Z").first.to_s
# => "2017-10-05T18:30:00+00:00" expected: "2017-10-06T18:30:00+00:00"
ISO8601::TimeInterval.new("P3D/2017-12-06T18:30:00Z").first.to_s
# => "2016-12-03T18:30:00+00:00" expected: "2017-12-03T18:30:00+00:00"

ISO8601::TimeInterval.new("P1Y/2017-11-06T18:30:00Z").first.to_s
# => "2016-11-06T18:30:00+00:00" correct
ISO8601::TimeInterval.new("P2M/2017-11-06T18:30:00Z").first.to_s
# => "2017-09-06T18:30:00+00:00" correct
ISO8601::TimeInterval.new("P3D/2017-11-06T18:30:00Z").first.to_s
# => "2017-11-03T18:30:00+00:00" correct
```
I have traced the problem to `ISO8601::Months#to_seconds` (called from `ISO8601::DateInterval#to_seconds`, which in turn is called from `ISO8601::TimeInterval#tuple_by_end`).

The root of the problem lies in incorrect values returned by `ISO8601::Months#zero_calculate` and `ISO8601::Months#calculate` (called from `ISO8601::Months#to_seconds`):

I calculated the return value of `ISO8601::Months#zero_calculate` with base dates from every month and found it returns `0.0` for all but December, in which case it returns `31536000.0` (1 year). I'm confused why this method is necessary: if the `months` atom is zero, then my gut feeling is that `to_seconds` should return zero.

There's a lot of logic in `ISO8601::Months#calculate`, and I did not have time to inspect it. It seems that the value returned by this calculation is off by a day when the base month is December.

**Comment by arnau** [comment]
Thanks for the detailed report @komputerwiz! I'll have a look soon.

**Comment by komputerwiz** [comment]
You're welcome! Great job on the library! I only wish the built-in Date/Time libraries supported ISO 8601 this well... Maybe in a future release.

**Comment by arnau** [comment]
@komputerwiz I've done a first round (see branch `time-intervals-december`). The issue was due not one but two errors in the implementation of Durations. And, as you correctly suspected, `#zero_calculate` was useless (used to be a thing when Duration was doing partially the job of a TimeInterval.

So, the current status should work with the examples you put in this issue. The thing I have to look into with a bit more time is how to do the calculation with something like `P1.5Y/2017-01-01T00:00:00Z'. In the meanwhile, if you have the chance to test the fix I made to double check it is actually a fix it would be really helpful. Thanks!

**Comment by komputerwiz** [comment]
Looks good! Thanks for addressing this so quickly.

I haven't seen decimal atoms used in any examples, so I'm curious if they're part of the spec. A duration like `P1.5Y` would be difficult to calculate for both humans and machines: most people would probably think to use `P1Y6M` anyway. Decimals make sense for fractional seconds since there's nothing smaller than the "seconds" atom, so that could be useful.

**Comment by arnau** [comment]
You are right, the only elements that can have fractions are the three time elements and only the last one of the expression. My mistake :)

Fractions of a second are supported already so it shouldn't be a problem. I'll clean up the house and prepare 0.9.2.

**Comment by arnau** [comment]
It'll be 0.10.0, it could break some consumers.
